export const SET_SESSION = 'SET_SESSION';
export const UNSET_SESSION = 'UNSET_SESSION';

export const SET_USER_INFO = 'SET_USER_INFO';

export const SET_SHARE_INFORMATION = 'SET_SHARE_INFORMATION';
export const UPDATE_SHARE_INFO = 'UPDATE_SHARE_INFO';
